trigger:
- main

pool:
  name: Default   # self-hosted agent

steps:
- script: |
    python --version
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m nuitka --standalone --onefile --enable-plugin=pyside6 --windows-disable-console hello.py
  displayName: 'Build EXE with Nuitka'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'hello.exe'
    ArtifactName: 'drop'
    publishLocation: 'Container'
