trigger:
- main

pool:
  name: 'Default'   # your self-hosted agent pool

variables:
- group: Azure IDs   # Make sure you created this variable group in DevOps

steps:
# Step 1: Checkout code
- checkout: self

# Step 2: Install dependencies (uses your system Python)
- script: |
    python -m pip install --upgrade pip
    pip install nuitka pyside6
  displayName: 'Install Python packages'

# Step 3: Build EXE with Nuitka using MSVC
- script: |
    python -m nuitka --standalone --enable-plugin=pyside6 --msvc=latest hello.py
  displayName: 'Build EXE with Nuitka (MSVC)'

# Step 4: Sign the EXE using Azure Trusted Signing via PowerShell
- powershell: |
    Write-Host "Signing EXE with Azure Trusted Signing..."
    signtool sign `
      /tr http://timestamp.digicert.com `
      /fd SHA256 `
      /a `
      /v `
      /debug `
      /n "CN=johnrysalroselgmail.onmicrosoft.com, O=johnrysalroselgmail.onmicrosoft.com, OU=HelloWorldNuitkaRysal, STREET=F. Cruz St., L=Pasay City, C=PH" `
      "$(Build.SourcesDirectory)\hello.dist\hello.exe"
  displayName: 'Code Sign EXE'
  env:
    AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
    AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
    AZURE_TENANT_ID: $(AZURE_TENANT_ID)
    AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)

# Step 5: Publish artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)\hello.dist'
    artifactName: 'hello-exe'
  displayName: 'Publish EXE artifact'
