trigger:
- main

pool:
  name: 'Default'   # your self-hosted agent pool

variables:
- group: Azure IDs   # 🔹 Make sure this variable group contains:

steps:
# Step 1: Checkout code
- checkout: self

# Step 2: Install dependencies (uses your system Python)
- script: |
    python -m pip install --upgrade pip
    pip install nuitka pyside6
  displayName: 'Install Python packages'

# Step 3: Build EXE with Nuitka using MSVC
- script: |
    python -m nuitka --standalone --enable-plugin=pyside6 --msvc=latest hello.py
  displayName: 'Build EXE with Nuitka (MSVC)'

# Step 4: Install Azure Trusted Signing CLI
- powershell: |
    Write-Host "Installing Azure Trusted Signing CLI..."
    winget install --id Microsoft.AzureTrustedSigningClient -e --silent --accept-source-agreements --accept-package-agreements
  displayName: 'Install Azure Trusted Signing CLI'

# Step 5: Sign the EXE using Azure Trusted Signing CLI
- powershell: |
    Write-Host "Signing EXE with Azure Trusted Signing..."
    azuresigntool sign `
      --endpoint "https://eus.codesigning.azure.net/" `
      --certificate-profile "hello-world-nuitka-rysal" `
      --azure-key-vault-client-id $env:AZURE_CLIENT_ID `
      --azure-key-vault-client-secret $env:AZURE_CLIENT_SECRET `
      --azure-key-vault-tenant-id $env:AZURE_TENANT_ID `
      "$(Build.SourcesDirectory)\hello.dist\hello.exe"
  displayName: 'Code Sign EXE with Azure Trusted Signing'
  env:
    AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
    AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
    AZURE_TENANT_ID: $(AZURE_TENANT_ID)
    AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)

# Step 6: Publish artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)\hello.dist'
    artifactName: 'hello-exe'
  displayName: 'Publish EXE artifact'
