trigger:
- main

pool:
  name: 'Default'   # your self-hosted agent pool

variables:
- group: Azure IDs   # 🔹 Make sure this variable group contains:

steps:
# Step 1: Checkout code
- checkout: self

# Step 2: Install dependencies (uses your system Python)
- script: |
    python -m pip install --upgrade pip
    pip install nuitka pyside6
  displayName: 'Install Python packages'

# Step 3: Build EXE with Nuitka using MSVC
- script: |
    python -m nuitka --standalone --enable-plugin=pyside6 --msvc=latest hello.py
  displayName: 'Build EXE with Nuitka (MSVC)'

# Step 4: Sign EXE using Azure Trusted Signing
- task: TrustedSigning@0
  displayName: 'Sign EXE with Trusted Signing'
  inputs:
    AzureTenantID: '$(AZURE_TENANT_ID)'
    AzureClientID: '$(AZURE_CLIENT_ID)'
    AzureClientSecret: '$(AZURE_CLIENT_SECRET)'
    Endpoint: 'https://eus.codesigning.azure.net/'   # your Trusted Signing account endpoint
    TrustedSigningAccountName: 'hello-world-nuitka-rysal'  # your Trusted Signing account
    CertificateProfileName: 'hello-world-nuitka-profile'    # your certificate profile name
    FilesFolder: '$(Build.SourcesDirectory)/hello.dist'
    FilesFolderFilter: 'hello.exe'      # can also use *.exe to sign multiple files
    FilesFolderRecurse: false
    FileDigest: 'SHA256'
    TimestampRfc3161: 'http://timestamp.digicert.com'
    TimestampDigest: 'SHA256'

# Step 5: Publish artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)\hello.dist'
    artifactName: 'hello-exe'
  displayName: 'Publish EXE artifact'
