trigger:
- main   # pipeline runs when you push to main branch

pool:
  name: Default

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'   # pick the Python version you want
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m nuitka --standalone --onefile --enable-plugin=pyside6 --windows-disable-console hello.py
  displayName: 'Build EXE with Nuitka'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'hello.exe'
    ArtifactName: 'drop'
    publishLocation: 'Container'
