trigger:
- main

pool:
  name: 'Default'     # Replace with your self-hosted agent pool name if different

steps:
# Step 1: Checkout code
- checkout: self

# Step 2: Install dependencies (uses your system Python)
- script: |
    python -m pip install --upgrade pip
    pip install nuitka pyside6
  displayName: 'Install Python packages'

# Step 3: Build EXE with Nuitka using MSVC
- script: |
    python -m nuitka --standalone --enable-plugin=pyside6 --msvc=latest hello.py
  displayName: 'Build EXE with Nuitka (MSVC)'

# Step 4: Publish artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)\hello.dist'
    artifactName: 'hello-exe'
  displayName: 'Publish EXE artifact'
