trigger:
- main

pool:
  name: 'Default'   # your self-hosted agent pool

variables:
- group: Azure IDs   # 🔹 Make sure this variable group contains:

steps:
# Step 1: Checkout code
- checkout: self

# Step 2: Install dependencies (uses your system Python)
- script: |
    python -m pip install --upgrade pip
    pip install nuitka pyside6
  displayName: 'Install Python packages'

# Step 3: Build EXE with Nuitka using MSVC
- script: |
    python -m nuitka --standalone --enable-plugin=pyside6 --msvc=latest hello.py
  displayName: 'Build EXE with Nuitka (MSVC)'

# Step 4: Sign the EXE using Azure Trusted Signing CLI
- powershell: |
    Write-Host "Signing EXE with Azure Trusted Signing..."
    C:\Users\Rysal\AzureSignTool-x64.exe sign `
      --endpoint "https://eus.codesigning.azure.net/" `
      --certificate-profile "hello-world-nuitka-rysal" `
      --azure-key-vault-client-id $(AZURE_CLIENT_ID) `
      --azure-key-vault-client-secret $(AZURE_CLIENT_SECRET) `
      --azure-key-vault-tenant-id $(AZURE_TENANT_ID) `
      "$(Build.SourcesDirectory)\hello.dist\hello.exe"
  displayName: 'Sign EXE with Azure Trusted Signing'

# Step 5: Publish artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)\hello.dist'
    artifactName: 'hello-exe'
  displayName: 'Publish EXE artifact'
