trigger:
- main

pool:
  name: 'Default'     # 👈 Use your self-hosted agent pool name here

steps:
# Step 1: Checkout code
- checkout: self

# Step 2: (Optional) Use Python installed on your self-hosted machine
# If Python is already installed and in PATH, you can skip this task
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    addToPath: true
  displayName: 'Setup Python 3.12 (if needed)'

# Step 3: Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install nuitka pyside6
  displayName: 'Install Python packages'

# Step 4: Build EXE with Nuitka using MSVC
- script: |
    python -m nuitka --standalone --onefile --enable-plugin=pyside6 --msvc=latest hello.py
  displayName: 'Build EXE with Nuitka (MSVC)'

# Step 5: Publish artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)\hello.dist'
    artifactName: 'hello-exe'
  displayName: 'Publish EXE artifact'
